name: MockLocationApp
options:
  bundleIdPrefix: com.familytools
  xcodeVersion: '15.0'
targets:
  MockLocationApp:
    type: application
    platform: iOS
    deploymentTarget: '15.0'
    sources:
      - path: Sources
    resources:
      - path: Resources
    frameworks:
      - MapKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.familytools.mocklocation
        DEVELOPMENT_ASSET_PATHS: Resources
        SWIFT_VERSION: 5.9
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
    scheme:
      testTargets: []
